# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif

mainconfig:=$(config)

SOLUTIONS:=winreload winreload32 winreload64
SOLUTIONSCLEAN=$(addsuffix -clean,$(SOLUTIONS))

.PHONY: premake all clean distclean help $(SOLUTIONS) $(SOLUTIONSCLEAN)

all: $(SOLUTIONS)

$(SOLUTIONS):
	@echo "==== Building $@ ($(config)) ===="
	@${MAKE} --no-print-directory -C .  -f $@.make \
		$(if $(findstring 64, $@), config=$(mainconfig)_w64, config=$(mainconfig)_w32)

clean: $(SOLUTIONSCLEAN)
	@echo "==== Removing bin and obj directories ===="
	@rm -rf bin obj

%-clean:
	@echo "==== Cleaning $@ ===="
	@${MAKE} --no-print-directory -C . -f $@.make clean

distclean: clean
	@echo "==== Cleaning Distribution ===="
	@rm -f *.make

premake:
	@echo "==== Generating sub-makefiles ===="
	@premake4 gmake

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   distclean"
	@echo "   clean"
	@echo ""
