# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug_w32
endif
export config

PROJECTS := WinReloadLib32 WinReloadDrv32

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

WinReloadLib32: 
	@echo "==== Building WinReloadLib32 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f WinReloadLib32.make

WinReloadDrv32: WinReloadLib32
	@echo "==== Building WinReloadDrv32 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f WinReloadDrv32.make

clean:
	@${MAKE} --no-print-directory -C . -f WinReloadLib32.make clean
	@${MAKE} --no-print-directory -C . -f WinReloadDrv32.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug_w32"
	@echo "   release_w32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   WinReloadLib32"
	@echo "   WinReloadDrv32"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
