# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug_w32
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug_w32)
  CC         = i686-w64-mingw32-gcc
  CXX        = i686-w64-mingw32-g++
  AR         = i686-w64-mingw32-ar
  OBJDIR     = obj/gui/w32/debug
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/WinReload.exe
  DEFINES   += 
  INCLUDES  += -Isrc/include -I/opt/i686-w64-mingw32/lib/wx/include/i686-w64-mingw32-msw-unicode-3.0 -I/opt/i686-w64-mingw32/include/wx-3.0
  CPPFLAGS  +=  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -std=gnu++11
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -mwindows -L/opt/i686-w64-mingw32/lib
  LIBS      += -lwx_mswu-3.0-i686-w64-mingw32 -lwx_mswu_gl-3.0-i686-w64-mingw32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_w32)
  CC         = i686-w64-mingw32-gcc
  CXX        = i686-w64-mingw32-g++
  AR         = i686-w64-mingw32-ar
  OBJDIR     = obj/gui/w32/release
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/WinReload.exe
  DEFINES   += 
  INCLUDES  += -Isrc/include -I/opt/i686-w64-mingw32/lib/wx/include/i686-w64-mingw32-msw-unicode-3.0 -I/opt/i686-w64-mingw32/include/wx-3.0
  CPPFLAGS  +=  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -std=gnu++11
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -mwindows -L/opt/i686-w64-mingw32/lib
  LIBS      += -lwx_mswu-3.0-i686-w64-mingw32 -lwx_mswu_gl-3.0-i686-w64-mingw32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/app.o \
	$(OBJDIR)/childproc.o \
	$(OBJDIR)/maingui.o \
	$(OBJDIR)/myframe1.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking WinReload
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning WinReload
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/app.o: src/reload/app.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/childproc.o: src/reload/childproc.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/maingui.o: src/reload/maingui.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/myframe1.o: src/reload/myframe1.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
