# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug_w64
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug_w64)
  CC         = x86_64-w64-mingw32-gcc
  CXX        = x86_64-w64-mingw32-g++
  AR         = x86_64-w64-mingw32-ar
  OBJDIR     = obj/drv/64/w64/debug
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/WinReloadDrv64.exe
  DEFINES   += 
  INCLUDES  += -Isrc/include -Isrc/drv/lib
  CPPFLAGS  +=  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -std=gnu++11
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -Lbin
  LIBS      += -lWinReloadLib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += bin/libWinReloadLib64.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_w64)
  CC         = x86_64-w64-mingw32-gcc
  CXX        = x86_64-w64-mingw32-g++
  AR         = x86_64-w64-mingw32-ar
  OBJDIR     = obj/drv/64/w64/release
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/WinReloadDrv64.exe
  DEFINES   += 
  INCLUDES  += -Isrc/include -Isrc/drv/lib
  CPPFLAGS  +=  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -std=gnu++11
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -Lbin
  LIBS      += -lWinReloadLib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += bin/libWinReloadLib64.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/main.o \
	$(OBJDIR)/winbits.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking WinReloadDrv64
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning WinReloadDrv64
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/main.o: src/drv/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/winbits.o: src/drv/winbits.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
