# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug_w64
endif
export config

PROJECTS := WinReloadLib64 WinReloadDrv64

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

WinReloadLib64: 
	@echo "==== Building WinReloadLib64 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f WinReloadLib64.make

WinReloadDrv64: WinReloadLib64
	@echo "==== Building WinReloadDrv64 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f WinReloadDrv64.make

clean:
	@${MAKE} --no-print-directory -C . -f WinReloadLib64.make clean
	@${MAKE} --no-print-directory -C . -f WinReloadDrv64.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug_w64"
	@echo "   release_w64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   WinReloadLib64"
	@echo "   WinReloadDrv64"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
